let a=5;
let b=10;
console.log("a=",a);
console.log("b=",b);
try{// it used to continue the code
console.log("c=",c);
}
catch(err){ //it used to catch error in particular line
    console.log(err);
}
console.log("a+b=",a+b);


